- name: "manage worker1 and 2"
  hosts: localhost
  become: true
  tasks:
  - name: "ensure Amit user absent"
    user:
      name: amit
      state: absent
  - name: "ensure Alex user absent"
    user:
      name: alex
      state: absent
  - name: "ensure Ingrid user exists"
    user:
      name: ingrid
      state: present  
